/*
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * API version: 1.20230615090446
 * Contact: support@able.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ablesdk

import (
	"encoding/json"
)

// V1Upload An Able upload.
type V1Upload struct {
	// The resource name of the upload.
	Name *string `json:"name,omitempty"`
}

// NewV1Upload instantiates a new V1Upload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1Upload() *V1Upload {
	this := V1Upload{}
	return &this
}

// NewV1UploadWithDefaults instantiates a new V1Upload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1UploadWithDefaults() *V1Upload {
	this := V1Upload{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1Upload) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1Upload) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1Upload) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1Upload) SetName(v string) {
	o.Name = &v
}

func (o V1Upload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableV1Upload struct {
	value *V1Upload
	isSet bool
}

func (v NullableV1Upload) Get() *V1Upload {
	return v.value
}

func (v *NullableV1Upload) Set(val *V1Upload) {
	v.value = val
	v.isSet = true
}

func (v NullableV1Upload) IsSet() bool {
	return v.isSet
}

func (v *NullableV1Upload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1Upload(val *V1Upload) *NullableV1Upload {
	return &NullableV1Upload{value: val, isSet: true}
}

func (v NullableV1Upload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1Upload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


