/*
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * API version: 1.20230727053012
 * Contact: support@able.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ablesdk

import (
	"encoding/json"
)

// V1AcquireDocumentContentRequestV1Body struct for V1AcquireDocumentContentRequestV1Body
type V1AcquireDocumentContentRequestV1Body struct {
	// The expected amount of time for task execution.
	ExpectedExecutionDuration string `json:"expectedExecutionDuration"`
}

// NewV1AcquireDocumentContentRequestV1Body instantiates a new V1AcquireDocumentContentRequestV1Body object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AcquireDocumentContentRequestV1Body(expectedExecutionDuration string, ) *V1AcquireDocumentContentRequestV1Body {
	this := V1AcquireDocumentContentRequestV1Body{}
	this.ExpectedExecutionDuration = expectedExecutionDuration
	return &this
}

// NewV1AcquireDocumentContentRequestV1BodyWithDefaults instantiates a new V1AcquireDocumentContentRequestV1Body object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AcquireDocumentContentRequestV1BodyWithDefaults() *V1AcquireDocumentContentRequestV1Body {
	this := V1AcquireDocumentContentRequestV1Body{}
	return &this
}

// GetExpectedExecutionDuration returns the ExpectedExecutionDuration field value
func (o *V1AcquireDocumentContentRequestV1Body) GetExpectedExecutionDuration() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ExpectedExecutionDuration
}

// GetExpectedExecutionDurationOk returns a tuple with the ExpectedExecutionDuration field value
// and a boolean to check if the value has been set.
func (o *V1AcquireDocumentContentRequestV1Body) GetExpectedExecutionDurationOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ExpectedExecutionDuration, true
}

// SetExpectedExecutionDuration sets field value
func (o *V1AcquireDocumentContentRequestV1Body) SetExpectedExecutionDuration(v string) {
	o.ExpectedExecutionDuration = v
}

func (o V1AcquireDocumentContentRequestV1Body) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["expectedExecutionDuration"] = o.ExpectedExecutionDuration
	}
	return json.Marshal(toSerialize)
}

type NullableV1AcquireDocumentContentRequestV1Body struct {
	value *V1AcquireDocumentContentRequestV1Body
	isSet bool
}

func (v NullableV1AcquireDocumentContentRequestV1Body) Get() *V1AcquireDocumentContentRequestV1Body {
	return v.value
}

func (v *NullableV1AcquireDocumentContentRequestV1Body) Set(val *V1AcquireDocumentContentRequestV1Body) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AcquireDocumentContentRequestV1Body) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AcquireDocumentContentRequestV1Body) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AcquireDocumentContentRequestV1Body(val *V1AcquireDocumentContentRequestV1Body) *NullableV1AcquireDocumentContentRequestV1Body {
	return &NullableV1AcquireDocumentContentRequestV1Body{value: val, isSet: true}
}

func (v NullableV1AcquireDocumentContentRequestV1Body) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AcquireDocumentContentRequestV1Body) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


