/*
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * API version: 1.20230615090446
 * Contact: support@able.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ablesdk

import (
	"encoding/json"
)

// V1Relationship An Able relationship.
type V1Relationship struct {
	// The resource name of the relationship.
	Name *string `json:"name,omitempty"`
}

// NewV1Relationship instantiates a new V1Relationship object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1Relationship() *V1Relationship {
	this := V1Relationship{}
	return &this
}

// NewV1RelationshipWithDefaults instantiates a new V1Relationship object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1RelationshipWithDefaults() *V1Relationship {
	this := V1Relationship{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1Relationship) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1Relationship) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1Relationship) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1Relationship) SetName(v string) {
	o.Name = &v
}

func (o V1Relationship) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableV1Relationship struct {
	value *V1Relationship
	isSet bool
}

func (v NullableV1Relationship) Get() *V1Relationship {
	return v.value
}

func (v *NullableV1Relationship) Set(val *V1Relationship) {
	v.value = val
	v.isSet = true
}

func (v NullableV1Relationship) IsSet() bool {
	return v.isSet
}

func (v *NullableV1Relationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1Relationship(val *V1Relationship) *NullableV1Relationship {
	return &NullableV1Relationship{value: val, isSet: true}
}

func (v NullableV1Relationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1Relationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


