/*
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * API version: 1.20230621235520
 * Contact: support@able.ai
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ablesdk

import (
	"encoding/json"
)

// V1CompleteDocumentVersionRequestProperties struct for V1CompleteDocumentVersionRequestProperties
type V1CompleteDocumentVersionRequestProperties struct {
	Status V1DocumentVersionStatus `json:"status"`
	// Any error message generated during processing, empty if status is COMPLETE.
	LastError *string `json:"lastError,omitempty"`
	// Any attributes extracted from the document during processing.
	Attributes *[]V1Attribute `json:"attributes,omitempty"`
}

// NewV1CompleteDocumentVersionRequestProperties instantiates a new V1CompleteDocumentVersionRequestProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1CompleteDocumentVersionRequestProperties(status V1DocumentVersionStatus, ) *V1CompleteDocumentVersionRequestProperties {
	this := V1CompleteDocumentVersionRequestProperties{}
	this.Status = status
	return &this
}

// NewV1CompleteDocumentVersionRequestPropertiesWithDefaults instantiates a new V1CompleteDocumentVersionRequestProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1CompleteDocumentVersionRequestPropertiesWithDefaults() *V1CompleteDocumentVersionRequestProperties {
	this := V1CompleteDocumentVersionRequestProperties{}
	var status V1DocumentVersionStatus = DOCUMENT_VERSION_STATUS_UNSPECIFIED
	this.Status = status
	return &this
}

// GetStatus returns the Status field value
func (o *V1CompleteDocumentVersionRequestProperties) GetStatus() V1DocumentVersionStatus {
	if o == nil  {
		var ret V1DocumentVersionStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V1CompleteDocumentVersionRequestProperties) GetStatusOk() (*V1DocumentVersionStatus, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V1CompleteDocumentVersionRequestProperties) SetStatus(v V1DocumentVersionStatus) {
	o.Status = v
}

// GetLastError returns the LastError field value if set, zero value otherwise.
func (o *V1CompleteDocumentVersionRequestProperties) GetLastError() string {
	if o == nil || o.LastError == nil {
		var ret string
		return ret
	}
	return *o.LastError
}

// GetLastErrorOk returns a tuple with the LastError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1CompleteDocumentVersionRequestProperties) GetLastErrorOk() (*string, bool) {
	if o == nil || o.LastError == nil {
		return nil, false
	}
	return o.LastError, true
}

// HasLastError returns a boolean if a field has been set.
func (o *V1CompleteDocumentVersionRequestProperties) HasLastError() bool {
	if o != nil && o.LastError != nil {
		return true
	}

	return false
}

// SetLastError gets a reference to the given string and assigns it to the LastError field.
func (o *V1CompleteDocumentVersionRequestProperties) SetLastError(v string) {
	o.LastError = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *V1CompleteDocumentVersionRequestProperties) GetAttributes() []V1Attribute {
	if o == nil || o.Attributes == nil {
		var ret []V1Attribute
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1CompleteDocumentVersionRequestProperties) GetAttributesOk() (*[]V1Attribute, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *V1CompleteDocumentVersionRequestProperties) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []V1Attribute and assigns it to the Attributes field.
func (o *V1CompleteDocumentVersionRequestProperties) SetAttributes(v []V1Attribute) {
	o.Attributes = &v
}

func (o V1CompleteDocumentVersionRequestProperties) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["status"] = o.Status
	}
	if o.LastError != nil {
		toSerialize["lastError"] = o.LastError
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableV1CompleteDocumentVersionRequestProperties struct {
	value *V1CompleteDocumentVersionRequestProperties
	isSet bool
}

func (v NullableV1CompleteDocumentVersionRequestProperties) Get() *V1CompleteDocumentVersionRequestProperties {
	return v.value
}

func (v *NullableV1CompleteDocumentVersionRequestProperties) Set(val *V1CompleteDocumentVersionRequestProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableV1CompleteDocumentVersionRequestProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableV1CompleteDocumentVersionRequestProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1CompleteDocumentVersionRequestProperties(val *V1CompleteDocumentVersionRequestProperties) *NullableV1CompleteDocumentVersionRequestProperties {
	return &NullableV1CompleteDocumentVersionRequestProperties{value: val, isSet: true}
}

func (v NullableV1CompleteDocumentVersionRequestProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1CompleteDocumentVersionRequestProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


