/* tslint:disable */
/* eslint-disable */
/**
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230621235520
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1Document,
    V1DocumentFromJSON,
    V1DocumentFromJSONTyped,
    V1DocumentToJSON,
} from './';

/**
 * Request to create a new DocumentVersion.
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * A list of documents to be added to the DocumentVersion.
     * @type {Array<V1Document>}
     * @memberof InlineObject
     */
    documents?: Array<V1Document>;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documents': !exists(json, 'documents') ? undefined : ((json['documents'] as Array<any>).map(V1DocumentFromJSON)),
    };
}

export function InlineObjectToJSON(value?: InlineObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documents': value.documents === undefined ? undefined : ((value.documents as Array<any>).map(V1DocumentToJSON)),
    };
}


