/* tslint:disable */
/* eslint-disable */
/**
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230621235520
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AcquireDocumentVersionRequestProperties
 */
export interface V1AcquireDocumentVersionRequestProperties {
    /**
     * The expected amount of time for task execution.
     * @type {string}
     * @memberof V1AcquireDocumentVersionRequestProperties
     */
    expectedExecutionDuration: string;
}

export function V1AcquireDocumentVersionRequestPropertiesFromJSON(json: any): V1AcquireDocumentVersionRequestProperties {
    return V1AcquireDocumentVersionRequestPropertiesFromJSONTyped(json, false);
}

export function V1AcquireDocumentVersionRequestPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AcquireDocumentVersionRequestProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expectedExecutionDuration': json['expectedExecutionDuration'],
    };
}

export function V1AcquireDocumentVersionRequestPropertiesToJSON(value?: V1AcquireDocumentVersionRequestProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expectedExecutionDuration': value.expectedExecutionDuration,
    };
}


