/* tslint:disable */
/* eslint-disable */
/**
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230621235520
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1Attribute,
    V1AttributeFromJSON,
    V1AttributeFromJSONTyped,
    V1AttributeToJSON,
    V1DocumentVersionStatus,
    V1DocumentVersionStatusFromJSON,
    V1DocumentVersionStatusFromJSONTyped,
    V1DocumentVersionStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface V1CompleteDocumentVersionRequestProperties
 */
export interface V1CompleteDocumentVersionRequestProperties {
    /**
     * 
     * @type {V1DocumentVersionStatus}
     * @memberof V1CompleteDocumentVersionRequestProperties
     */
    status: V1DocumentVersionStatus;
    /**
     * Any error message generated during processing, empty if status is
     * COMPLETE.
     * @type {string}
     * @memberof V1CompleteDocumentVersionRequestProperties
     */
    lastError?: string;
    /**
     * Any attributes extracted from the document during processing.
     * @type {Array<V1Attribute>}
     * @memberof V1CompleteDocumentVersionRequestProperties
     */
    attributes?: Array<V1Attribute>;
}

export function V1CompleteDocumentVersionRequestPropertiesFromJSON(json: any): V1CompleteDocumentVersionRequestProperties {
    return V1CompleteDocumentVersionRequestPropertiesFromJSONTyped(json, false);
}

export function V1CompleteDocumentVersionRequestPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CompleteDocumentVersionRequestProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': V1DocumentVersionStatusFromJSON(json['status']),
        'lastError': !exists(json, 'lastError') ? undefined : json['lastError'],
        'attributes': !exists(json, 'attributes') ? undefined : ((json['attributes'] as Array<any>).map(V1AttributeFromJSON)),
    };
}

export function V1CompleteDocumentVersionRequestPropertiesToJSON(value?: V1CompleteDocumentVersionRequestProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': V1DocumentVersionStatusToJSON(value.status),
        'lastError': value.lastError,
        'attributes': value.attributes === undefined ? undefined : ((value.attributes as Array<any>).map(V1AttributeToJSON)),
    };
}


