/* tslint:disable */
/* eslint-disable */
/**
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230717220244
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1Document,
    V1DocumentFromJSON,
    V1DocumentFromJSONTyped,
    V1DocumentToJSON,
} from './';

/**
 * 
 * @export
 * @interface V1CreateDocumentContentRequestV1Body
 */
export interface V1CreateDocumentContentRequestV1Body {
    /**
     * A list of documents to be added to the DocumentContent.
     * @type {Array<V1Document>}
     * @memberof V1CreateDocumentContentRequestV1Body
     */
    documents?: Array<V1Document>;
}

export function V1CreateDocumentContentRequestV1BodyFromJSON(json: any): V1CreateDocumentContentRequestV1Body {
    return V1CreateDocumentContentRequestV1BodyFromJSONTyped(json, false);
}

export function V1CreateDocumentContentRequestV1BodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateDocumentContentRequestV1Body {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documents': !exists(json, 'documents') ? undefined : ((json['documents'] as Array<any>).map(V1DocumentFromJSON)),
    };
}

export function V1CreateDocumentContentRequestV1BodyToJSON(value?: V1CreateDocumentContentRequestV1Body | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documents': value.documents === undefined ? undefined : ((value.documents as Array<any>).map(V1DocumentToJSON)),
    };
}


