/* tslint:disable */
/* eslint-disable */
/**
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230622180011
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1Attribute,
    V1AttributeFromJSON,
    V1AttributeFromJSONTyped,
    V1AttributeToJSON,
} from './';

/**
 * Represents a document content created for processing.
 * @export
 * @interface V1DocumentContent
 */
export interface V1DocumentContent {
    /**
     * The primary key of the document in the external system.
     * @type {string}
     * @memberof V1DocumentContent
     */
    externalPrimaryKey?: string;
    /**
     * Attributes associated with the document.
     * @type {Array<V1Attribute>}
     * @memberof V1DocumentContent
     */
    attributes?: Array<V1Attribute>;
}

export function V1DocumentContentFromJSON(json: any): V1DocumentContent {
    return V1DocumentContentFromJSONTyped(json, false);
}

export function V1DocumentContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DocumentContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'externalPrimaryKey': !exists(json, 'externalPrimaryKey') ? undefined : json['externalPrimaryKey'],
        'attributes': !exists(json, 'attributes') ? undefined : ((json['attributes'] as Array<any>).map(V1AttributeFromJSON)),
    };
}

export function V1DocumentContentToJSON(value?: V1DocumentContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'externalPrimaryKey': value.externalPrimaryKey,
        'attributes': value.attributes === undefined ? undefined : ((value.attributes as Array<any>).map(V1AttributeToJSON)),
    };
}


