/* tslint:disable */
/* eslint-disable */
/**
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230717220244
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Status of processing document content.
 * 
 *  - COMPLETE: Document processing has been successful.
 *  - ERROR: Document processing was not successful.
 * @export
 * @enum {string}
 */
export enum V1DocumentContentStatusV1 {
    DocumentContentStatusUnspecified = 'DOCUMENT_CONTENT_STATUS_UNSPECIFIED',
    Complete = 'COMPLETE',
    Error = 'ERROR'
}

export function V1DocumentContentStatusV1FromJSON(json: any): V1DocumentContentStatusV1 {
    return V1DocumentContentStatusV1FromJSONTyped(json, false);
}

export function V1DocumentContentStatusV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DocumentContentStatusV1 {
    return json as V1DocumentContentStatusV1;
}

export function V1DocumentContentStatusV1ToJSON(value?: V1DocumentContentStatusV1 | null): any {
    return value as any;
}

