/*
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230622180011
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ableai.api.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The data type of an attribute.   - AUTO: Guess the attribute type based on its value.  - STRING: Interpret the attribute as a string.  - NUMBER: Interpret the attribute as a numeric value.
 */
@JsonAdapter(V1AttributeTypeV1.Adapter.class)
public enum V1AttributeTypeV1 {
  
  ATTRIBUTE_TYPE_UNSPECIFIED("ATTRIBUTE_TYPE_UNSPECIFIED"),
  
  AUTO("AUTO"),
  
  STRING("STRING"),
  
  NUMBER("NUMBER");

  private String value;

  V1AttributeTypeV1(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static V1AttributeTypeV1 fromValue(String value) {
    for (V1AttributeTypeV1 b : V1AttributeTypeV1.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<V1AttributeTypeV1> {
    @Override
    public void write(final JsonWriter jsonWriter, final V1AttributeTypeV1 enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public V1AttributeTypeV1 read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return V1AttributeTypeV1.fromValue(value);
    }
  }
}

