/*
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230621235520
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ableai.api.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.ableai.api.sdk.model.V1Attribute;
import com.ableai.api.sdk.model.V1DocumentVersionStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1CompleteDocumentVersionRequestProperties
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class V1CompleteDocumentVersionRequestProperties {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private V1DocumentVersionStatus status = V1DocumentVersionStatus.DOCUMENT_VERSION_STATUS_UNSPECIFIED;

  public static final String SERIALIZED_NAME_LAST_ERROR = "lastError";
  @SerializedName(SERIALIZED_NAME_LAST_ERROR)
  private String lastError;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private List<V1Attribute> attributes = null;


  public V1CompleteDocumentVersionRequestProperties status(V1DocumentVersionStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")

  public V1DocumentVersionStatus getStatus() {
    return status;
  }


  public void setStatus(V1DocumentVersionStatus status) {
    this.status = status;
  }


  public V1CompleteDocumentVersionRequestProperties lastError(String lastError) {
    
    this.lastError = lastError;
    return this;
  }

   /**
   * Any error message generated during processing, empty if status is COMPLETE.
   * @return lastError
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Any error message generated during processing, empty if status is COMPLETE.")

  public String getLastError() {
    return lastError;
  }


  public void setLastError(String lastError) {
    this.lastError = lastError;
  }


  public V1CompleteDocumentVersionRequestProperties attributes(List<V1Attribute> attributes) {
    
    this.attributes = attributes;
    return this;
  }

  public V1CompleteDocumentVersionRequestProperties addAttributesItem(V1Attribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<V1Attribute>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Any attributes extracted from the document during processing.
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Any attributes extracted from the document during processing.")

  public List<V1Attribute> getAttributes() {
    return attributes;
  }


  public void setAttributes(List<V1Attribute> attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1CompleteDocumentVersionRequestProperties v1CompleteDocumentVersionRequestProperties = (V1CompleteDocumentVersionRequestProperties) o;
    return Objects.equals(this.status, v1CompleteDocumentVersionRequestProperties.status) &&
        Objects.equals(this.lastError, v1CompleteDocumentVersionRequestProperties.lastError) &&
        Objects.equals(this.attributes, v1CompleteDocumentVersionRequestProperties.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, lastError, attributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1CompleteDocumentVersionRequestProperties {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lastError: ").append(toIndentedString(lastError)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

