/*
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230621235520
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ableai.api.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Status of processing a document version.   - COMPLETE: Document processing has been successful.  - ERROR: Document processing was not successful.
 */
@JsonAdapter(V1DocumentVersionStatus.Adapter.class)
public enum V1DocumentVersionStatus {
  
  DOCUMENT_VERSION_STATUS_UNSPECIFIED("DOCUMENT_VERSION_STATUS_UNSPECIFIED"),
  
  COMPLETE("COMPLETE"),
  
  ERROR("ERROR");

  private String value;

  V1DocumentVersionStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static V1DocumentVersionStatus fromValue(String value) {
    for (V1DocumentVersionStatus b : V1DocumentVersionStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<V1DocumentVersionStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final V1DocumentVersionStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public V1DocumentVersionStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return V1DocumentVersionStatus.fromValue(value);
    }
  }
}

