=begin
#Able API

#SDK for building integrations with Able.

The version of the OpenAPI document: 1.20230628184958
Contact: support@able.ai
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module AbleSDK
  class V1DataTransferDirectionV1
    DATA_TRANSFER_DIRECTION_UNSPECIFIED = "DATA_TRANSFER_DIRECTION_UNSPECIFIED".freeze
    TO_ABLE = "TO_ABLE".freeze
    TO_EXTERNAL = "TO_EXTERNAL".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = V1DataTransferDirectionV1.constants.select { |c| V1DataTransferDirectionV1::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #V1DataTransferDirectionV1" if constantValues.empty?
      value
    end
  end
end
