<?php
/**
 * V1DataTransferDirectionV1
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230717220244
 * Contact: support@able.ai
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1DataTransferDirectionV1 Class Doc Comment
 *
 * @category Class
 * @description Direction of data transfer.   - TO_ABLE: Data is transfered from an external source to Able.  - TO_EXTERNAL: Data is transfered from Able to an external source.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1DataTransferDirectionV1
{
    /**
     * Possible values of this enum
     */
    const DATA_TRANSFER_DIRECTION_UNSPECIFIED = 'DATA_TRANSFER_DIRECTION_UNSPECIFIED';
    const TO_ABLE = 'TO_ABLE';
    const TO_EXTERNAL = 'TO_EXTERNAL';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DATA_TRANSFER_DIRECTION_UNSPECIFIED,
            self::TO_ABLE,
            self::TO_EXTERNAL,
        ];
    }
}


