<?php
/**
 * V1DocumentVersionStatus
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230621235520
 * Contact: support@able.ai
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1DocumentVersionStatus Class Doc Comment
 *
 * @category Class
 * @description Status of processing a document version.   - COMPLETE: Document processing has been successful.  - ERROR: Document processing was not successful.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1DocumentVersionStatus
{
    /**
     * Possible values of this enum
     */
    const DOCUMENT_VERSION_STATUS_UNSPECIFIED = 'DOCUMENT_VERSION_STATUS_UNSPECIFIED';
    const COMPLETE = 'COMPLETE';
    const ERROR = 'ERROR';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DOCUMENT_VERSION_STATUS_UNSPECIFIED,
            self::COMPLETE,
            self::ERROR,
        ];
    }
}


