=begin
#Able API

#SDK for building integrations with Able.

The version of the OpenAPI document: 1.20230614220956
Contact: support@able.ai
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

module AbleSDK
  VERSION = '1.0.0'
end
