/*
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230628184958
 * Contact: support@able.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Able.Sdk.Client.OpenAPIDateConverter;

namespace Able.Sdk.Model
{
    /// <summary>
    /// Direction of data transfer.   - TO_ABLE: Data is transfered from an external source to Able.  - TO_EXTERNAL: Data is transfered from Able to an external source.
    /// </summary>
    /// <value>Direction of data transfer.   - TO_ABLE: Data is transfered from an external source to Able.  - TO_EXTERNAL: Data is transfered from Able to an external source.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum V1DataTransferDirectionV1
    {
        /// <summary>
        /// Enum DATATRANSFERDIRECTIONUNSPECIFIED for value: DATA_TRANSFER_DIRECTION_UNSPECIFIED
        /// </summary>
        [EnumMember(Value = "DATA_TRANSFER_DIRECTION_UNSPECIFIED")]
        DATATRANSFERDIRECTIONUNSPECIFIED = 1,

        /// <summary>
        /// Enum TOABLE for value: TO_ABLE
        /// </summary>
        [EnumMember(Value = "TO_ABLE")]
        TOABLE = 2,

        /// <summary>
        /// Enum TOEXTERNAL for value: TO_EXTERNAL
        /// </summary>
        [EnumMember(Value = "TO_EXTERNAL")]
        TOEXTERNAL = 3

    }

}
