/*
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230621235520
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ableai.api.sdk.model;

import com.ableai.api.sdk.model.V1DataTransferDirection;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V1AcquiredDocumentVersion
 */
public class V1AcquiredDocumentVersionTest {
    private final V1AcquiredDocumentVersion model = new V1AcquiredDocumentVersion();

    /**
     * Model tests for V1AcquiredDocumentVersion
     */
    @Test
    public void testV1AcquiredDocumentVersion() {
        // TODO: test V1AcquiredDocumentVersion
    }

    /**
     * Test the property 'documentVersionId'
     */
    @Test
    public void documentVersionIdTest() {
        // TODO: test documentVersionId
    }

    /**
     * Test the property 'externalPrimaryKey'
     */
    @Test
    public void externalPrimaryKeyTest() {
        // TODO: test externalPrimaryKey
    }

    /**
     * Test the property 'direction'
     */
    @Test
    public void directionTest() {
        // TODO: test direction
    }

    /**
     * Test the property 'uploadUrl'
     */
    @Test
    public void uploadUrlTest() {
        // TODO: test uploadUrl
    }

    /**
     * Test the property 'rawFileUrl'
     */
    @Test
    public void rawFileUrlTest() {
        // TODO: test rawFileUrl
    }

    /**
     * Test the property 'standardizedPdfUrl'
     */
    @Test
    public void standardizedPdfUrlTest() {
        // TODO: test standardizedPdfUrl
    }

    /**
     * Test the property 'contentUrl'
     */
    @Test
    public void contentUrlTest() {
        // TODO: test contentUrl
    }

    /**
     * Test the property 'acquiredBy'
     */
    @Test
    public void acquiredByTest() {
        // TODO: test acquiredBy
    }

    /**
     * Test the property 'acquiredTime'
     */
    @Test
    public void acquiredTimeTest() {
        // TODO: test acquiredTime
    }

    /**
     * Test the property 'acquiredDuration'
     */
    @Test
    public void acquiredDurationTest() {
        // TODO: test acquiredDuration
    }

}
