/*
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230622180011
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ableai.api.sdk.model;

import com.ableai.api.sdk.model.V1DocumentContentStatusV1;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V1CompletedDocumentContentV1
 */
public class V1CompletedDocumentContentV1Test {
    private final V1CompletedDocumentContentV1 model = new V1CompletedDocumentContentV1();

    /**
     * Model tests for V1CompletedDocumentContentV1
     */
    @Test
    public void testV1CompletedDocumentContentV1() {
        // TODO: test V1CompletedDocumentContentV1
    }

    /**
     * Test the property 'documentContentId'
     */
    @Test
    public void documentContentIdTest() {
        // TODO: test documentContentId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'lastError'
     */
    @Test
    public void lastErrorTest() {
        // TODO: test lastError
    }

    /**
     * Test the property 'acquiredBy'
     */
    @Test
    public void acquiredByTest() {
        // TODO: test acquiredBy
    }

    /**
     * Test the property 'acquiredTime'
     */
    @Test
    public void acquiredTimeTest() {
        // TODO: test acquiredTime
    }

    /**
     * Test the property 'completedBy'
     */
    @Test
    public void completedByTest() {
        // TODO: test completedBy
    }

    /**
     * Test the property 'completedTime'
     */
    @Test
    public void completedTimeTest() {
        // TODO: test completedTime
    }

}
