/*
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230621235520
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ableai.api.sdk.model;

import com.ableai.api.sdk.model.V1Attribute;
import com.ableai.api.sdk.model.V1DocumentVersionStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V1CompleteDocumentVersionRequestProperties
 */
public class V1CompleteDocumentVersionRequestPropertiesTest {
    private final V1CompleteDocumentVersionRequestProperties model = new V1CompleteDocumentVersionRequestProperties();

    /**
     * Model tests for V1CompleteDocumentVersionRequestProperties
     */
    @Test
    public void testV1CompleteDocumentVersionRequestProperties() {
        // TODO: test V1CompleteDocumentVersionRequestProperties
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'lastError'
     */
    @Test
    public void lastErrorTest() {
        // TODO: test lastError
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

}
