/*
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230622180011
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ableai.api.sdk.model;

import com.ableai.api.sdk.model.V1Document;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V1CreateDocumentContentRequestV1Body
 */
public class V1CreateDocumentContentRequestV1BodyTest {
    private final V1CreateDocumentContentRequestV1Body model = new V1CreateDocumentContentRequestV1Body();

    /**
     * Model tests for V1CreateDocumentContentRequestV1Body
     */
    @Test
    public void testV1CreateDocumentContentRequestV1Body() {
        // TODO: test V1CreateDocumentContentRequestV1Body
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

}
