"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230727053012
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.v1_document_content_status_v1 import V1DocumentContentStatusV1
globals()['V1DocumentContentStatusV1'] = V1DocumentContentStatusV1
from able_sdk.model.v1_completed_document_content_v1 import V1CompletedDocumentContentV1


class TestV1CompletedDocumentContentV1(unittest.TestCase):
    """V1CompletedDocumentContentV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1CompletedDocumentContentV1(self):
        """Test V1CompletedDocumentContentV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1CompletedDocumentContentV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
