"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230717220244
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.v1_acquire_document_content_request_v1_body import V1AcquireDocumentContentRequestV1Body


class TestV1AcquireDocumentContentRequestV1Body(unittest.TestCase):
    """V1AcquireDocumentContentRequestV1Body unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AcquireDocumentContentRequestV1Body(self):
        """Test V1AcquireDocumentContentRequestV1Body"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1AcquireDocumentContentRequestV1Body()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
