"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230621235520
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.v1_attribute import V1Attribute
from able_sdk.model.v1_document_version_status import V1DocumentVersionStatus
globals()['V1Attribute'] = V1Attribute
globals()['V1DocumentVersionStatus'] = V1DocumentVersionStatus
from able_sdk.model.v1_complete_document_version_request_properties import V1CompleteDocumentVersionRequestProperties


class TestV1CompleteDocumentVersionRequestProperties(unittest.TestCase):
    """V1CompleteDocumentVersionRequestProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1CompleteDocumentVersionRequestProperties(self):
        """Test V1CompleteDocumentVersionRequestProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1CompleteDocumentVersionRequestProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
