"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230621235520
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.v1_data_transfer_direction import V1DataTransferDirection
globals()['V1DataTransferDirection'] = V1DataTransferDirection
from able_sdk.model.v1_acquired_document_version import V1AcquiredDocumentVersion


class TestV1AcquiredDocumentVersion(unittest.TestCase):
    """V1AcquiredDocumentVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AcquiredDocumentVersion(self):
        """Test V1AcquiredDocumentVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1AcquiredDocumentVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
