"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230622180011
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.v1_attribute_type_v1 import V1AttributeTypeV1


class TestV1AttributeTypeV1(unittest.TestCase):
    """V1AttributeTypeV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AttributeTypeV1(self):
        """Test V1AttributeTypeV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1AttributeTypeV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
