"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230621235520
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.v1_attribute_type import V1AttributeType


class TestV1AttributeType(unittest.TestCase):
    """V1AttributeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1AttributeType(self):
        """Test V1AttributeType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1AttributeType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
