"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230623221606
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.protobuf_any import ProtobufAny
globals()['ProtobufAny'] = ProtobufAny
from able_sdk.model.rpc_status import RpcStatus


class TestRpcStatus(unittest.TestCase):
    """RpcStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRpcStatus(self):
        """Test RpcStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RpcStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
