"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230727053012
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.v1_data_transfer_direction_v1 import V1DataTransferDirectionV1


class TestV1DataTransferDirectionV1(unittest.TestCase):
    """V1DataTransferDirectionV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1DataTransferDirectionV1(self):
        """Test V1DataTransferDirectionV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1DataTransferDirectionV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
