"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230628184958
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.v1_attribute import V1Attribute
globals()['V1Attribute'] = V1Attribute
from able_sdk.model.v1_document_content import V1DocumentContent


class TestV1DocumentContent(unittest.TestCase):
    """V1DocumentContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1DocumentContent(self):
        """Test V1DocumentContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1DocumentContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
