"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230628184958
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import unittest

import able_sdk
from able_sdk.api.api_api import APIApi  # noqa: E501


class TestAPIApi(unittest.TestCase):
    """APIApi unit test stubs"""

    def setUp(self):
        self.api = APIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_a_pi_acquire_document_content_v1(self):
        """Test case for a_pi_acquire_document_content_v1

        Acquires a DocumentContent task. The task represents a document to be processed and once acquired, should be processed within the expected execution time. If the task is not completed within the expected time, it will be made available for acquisition by other workers.  # noqa: E501
        """
        pass

    def test_a_pi_complete_document_content_v1(self):
        """Test case for a_pi_complete_document_content_v1

        Completes a DocumentContent task. The task should be marked as complete after successful processing or if an error occurs during processing. If completed successfully, any extracted document attributes should be included in the completion request.  # noqa: E501
        """
        pass

    def test_a_pi_create_document_content_v1(self):
        """Test case for a_pi_create_document_content_v1

        Creates a new DocumentContent. The DocumentContent represents a document from an external system that needs to be processed.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
