"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230717220244
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.v1_attribute import V1Attribute
from able_sdk.model.v1_document_content_status_v1 import V1DocumentContentStatusV1
globals()['V1Attribute'] = V1Attribute
globals()['V1DocumentContentStatusV1'] = V1DocumentContentStatusV1
from able_sdk.model.v1_complete_document_content_request_v1_body import V1CompleteDocumentContentRequestV1Body


class TestV1CompleteDocumentContentRequestV1Body(unittest.TestCase):
    """V1CompleteDocumentContentRequestV1Body unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1CompleteDocumentContentRequestV1Body(self):
        """Test V1CompleteDocumentContentRequestV1Body"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1CompleteDocumentContentRequestV1Body()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
