"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230615090446
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.protobuf_any import ProtobufAny


class TestProtobufAny(unittest.TestCase):
    """ProtobufAny unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtobufAny(self):
        """Test ProtobufAny"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProtobufAny()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
