"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230628184958
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.v1_document import V1Document
globals()['V1Document'] = V1Document
from able_sdk.model.v1_create_document_content_request_v1_body import V1CreateDocumentContentRequestV1Body


class TestV1CreateDocumentContentRequestV1Body(unittest.TestCase):
    """V1CreateDocumentContentRequestV1Body unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1CreateDocumentContentRequestV1Body(self):
        """Test V1CreateDocumentContentRequestV1Body"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1CreateDocumentContentRequestV1Body()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
