"""
    Able API

    SDK for building integrations with Able.  # noqa: E501

    The version of the OpenAPI document: 1.20230623221606
    Contact: support@able.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import able_sdk
from able_sdk.model.v1_attribute_type_v1 import V1AttributeTypeV1
globals()['V1AttributeTypeV1'] = V1AttributeTypeV1
from able_sdk.model.v1_attribute import V1Attribute


class TestV1Attribute(unittest.TestCase):
    """V1Attribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1Attribute(self):
        """Test V1Attribute"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1Attribute()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
