/*
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230727053012
 * Contact: support@able.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Able.Sdk.Api;
using Able.Sdk.Model;
using Able.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Able.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing V1Attribute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1AttributeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1Attribute
        //private V1Attribute instance;

        public V1AttributeTests()
        {
            // TODO uncomment below to create an instance of V1Attribute
            //instance = new V1Attribute();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1Attribute
        /// </summary>
        [Fact]
        public void V1AttributeInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1Attribute
            //Assert.IsType<V1Attribute>(instance);
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
