/*
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230623221606
 * Contact: support@able.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Able.Sdk.Api;
using Able.Sdk.Model;
using Able.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Able.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing V1CompletedDocumentContentV1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1CompletedDocumentContentV1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1CompletedDocumentContentV1
        //private V1CompletedDocumentContentV1 instance;

        public V1CompletedDocumentContentV1Tests()
        {
            // TODO uncomment below to create an instance of V1CompletedDocumentContentV1
            //instance = new V1CompletedDocumentContentV1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1CompletedDocumentContentV1
        /// </summary>
        [Fact]
        public void V1CompletedDocumentContentV1InstanceTest()
        {
            // TODO uncomment below to test "IsType" V1CompletedDocumentContentV1
            //Assert.IsType<V1CompletedDocumentContentV1>(instance);
        }


        /// <summary>
        /// Test the property 'DocumentContentId'
        /// </summary>
        [Fact]
        public void DocumentContentIdTest()
        {
            // TODO unit test for the property 'DocumentContentId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'LastError'
        /// </summary>
        [Fact]
        public void LastErrorTest()
        {
            // TODO unit test for the property 'LastError'
        }
        /// <summary>
        /// Test the property 'AcquiredBy'
        /// </summary>
        [Fact]
        public void AcquiredByTest()
        {
            // TODO unit test for the property 'AcquiredBy'
        }
        /// <summary>
        /// Test the property 'AcquiredTime'
        /// </summary>
        [Fact]
        public void AcquiredTimeTest()
        {
            // TODO unit test for the property 'AcquiredTime'
        }
        /// <summary>
        /// Test the property 'CompletedBy'
        /// </summary>
        [Fact]
        public void CompletedByTest()
        {
            // TODO unit test for the property 'CompletedBy'
        }
        /// <summary>
        /// Test the property 'CompletedTime'
        /// </summary>
        [Fact]
        public void CompletedTimeTest()
        {
            // TODO unit test for the property 'CompletedTime'
        }

    }

}
