/*
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230622180011
 * Contact: support@able.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Able.Sdk.Api;
using Able.Sdk.Model;
using Able.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Able.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing V1CreateDocumentContentRequestV1Body
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1CreateDocumentContentRequestV1BodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1CreateDocumentContentRequestV1Body
        //private V1CreateDocumentContentRequestV1Body instance;

        public V1CreateDocumentContentRequestV1BodyTests()
        {
            // TODO uncomment below to create an instance of V1CreateDocumentContentRequestV1Body
            //instance = new V1CreateDocumentContentRequestV1Body();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1CreateDocumentContentRequestV1Body
        /// </summary>
        [Fact]
        public void V1CreateDocumentContentRequestV1BodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1CreateDocumentContentRequestV1Body
            //Assert.IsType<V1CreateDocumentContentRequestV1Body>(instance);
        }


        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Fact]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }

    }

}
