/*
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230621235520
 * Contact: support@able.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Able.Sdk.Api;
using Able.Sdk.Model;
using Able.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Able.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing V1DataTransferDirection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1DataTransferDirectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1DataTransferDirection
        //private V1DataTransferDirection instance;

        public V1DataTransferDirectionTests()
        {
            // TODO uncomment below to create an instance of V1DataTransferDirection
            //instance = new V1DataTransferDirection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1DataTransferDirection
        /// </summary>
        [Fact]
        public void V1DataTransferDirectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1DataTransferDirection
            //Assert.IsType<V1DataTransferDirection>(instance);
        }



    }

}
