/*
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230615090446
 * Contact: support@able.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Able.Sdk.Api;
using Able.Sdk.Model;
using Able.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Able.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing V1Relationship
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1RelationshipTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1Relationship
        //private V1Relationship instance;

        public V1RelationshipTests()
        {
            // TODO uncomment below to create an instance of V1Relationship
            //instance = new V1Relationship();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1Relationship
        /// </summary>
        [Fact]
        public void V1RelationshipInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1Relationship
            //Assert.IsType<V1Relationship>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
