=begin
#Able API

#SDK for building integrations with Able.

The version of the OpenAPI document: 1.20230621235520
Contact: support@able.ai
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

# Common files
require 'able_sdk/api_client'
require 'able_sdk/api_error'
require 'able_sdk/version'
require 'able_sdk/configuration'

# Models
require 'able_sdk/models/inline_object'
require 'able_sdk/models/protobuf_any'
require 'able_sdk/models/rpc_status'
require 'able_sdk/models/v1_acquire_document_version_request_properties'
require 'able_sdk/models/v1_acquired_document_version'
require 'able_sdk/models/v1_attribute'
require 'able_sdk/models/v1_attribute_type'
require 'able_sdk/models/v1_complete_document_version_request_properties'
require 'able_sdk/models/v1_completed_document_version'
require 'able_sdk/models/v1_data_transfer_direction'
require 'able_sdk/models/v1_document'
require 'able_sdk/models/v1_document_version'
require 'able_sdk/models/v1_document_version_status'

# APIs
require 'able_sdk/api/api_api'

module AbleSDK
  class << self
    # Customize default settings for the SDK using block.
    #   AbleSDK.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
