=begin
#Able API

#SDK for building integrations with Able.

The version of the OpenAPI document: 1.20230628184958
Contact: support@able.ai
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AbleSDK::V1AttributeTypeV1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AbleSDK::V1AttributeTypeV1 do
  let(:instance) { AbleSDK::V1AttributeTypeV1.new }

  describe 'test an instance of V1AttributeTypeV1' do
    it 'should create an instance of V1AttributeTypeV1' do
      expect(instance).to be_instance_of(AbleSDK::V1AttributeTypeV1)
    end
  end
end
