=begin
#Able API

#SDK for building integrations with Able.

The version of the OpenAPI document: 1.20230621235520
Contact: support@able.ai
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AbleSDK::V1AcquireDocumentVersionRequestProperties
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AbleSDK::V1AcquireDocumentVersionRequestProperties do
  let(:instance) { AbleSDK::V1AcquireDocumentVersionRequestProperties.new }

  describe 'test an instance of V1AcquireDocumentVersionRequestProperties' do
    it 'should create an instance of V1AcquireDocumentVersionRequestProperties' do
      expect(instance).to be_instance_of(AbleSDK::V1AcquireDocumentVersionRequestProperties)
    end
  end
  describe 'test attribute "expected_execution_duration"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
