=begin
#Able API

#SDK for building integrations with Able.

The version of the OpenAPI document: 1.20230622180011
Contact: support@able.ai
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AbleSDK::V1CompletedDocumentContentV1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AbleSDK::V1CompletedDocumentContentV1 do
  let(:instance) { AbleSDK::V1CompletedDocumentContentV1.new }

  describe 'test an instance of V1CompletedDocumentContentV1' do
    it 'should create an instance of V1CompletedDocumentContentV1' do
      expect(instance).to be_instance_of(AbleSDK::V1CompletedDocumentContentV1)
    end
  end
  describe 'test attribute "document_content_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "last_error"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "acquired_by"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "acquired_time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "completed_by"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "completed_time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
