=begin
#Able API

#SDK for building integrations with Able.

The version of the OpenAPI document: 1.20230622180011
Contact: support@able.ai
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AbleSDK::V1DocumentContent
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AbleSDK::V1DocumentContent do
  let(:instance) { AbleSDK::V1DocumentContent.new }

  describe 'test an instance of V1DocumentContent' do
    it 'should create an instance of V1DocumentContent' do
      expect(instance).to be_instance_of(AbleSDK::V1DocumentContent)
    end
  end
  describe 'test attribute "external_primary_key"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "attributes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
