<?php
/**
 * APIApi
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Able API
 *
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230622180011
 * Contact: support@able.ai
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * APIApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class APIApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex)
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation aPIAcquireDocumentContentV1
     *
     * Acquires a DocumentContent task. The task represents a document to be processed and once acquired, should be processed within the expected execution time. If the task is not completed within the expected time, it will be made available for acquisition by other workers.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  string $worker_name The name of the worker that will process the task. (required)
     * @param  \OpenAPI\Client\Model\V1AcquireDocumentContentRequestV1Body $body body (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\V1AcquiredDocumentContentV1|\OpenAPI\Client\Model\RpcStatus
     */
    public function aPIAcquireDocumentContentV1($extension_id, $worker_name, $body)
    {
        list($response) = $this->aPIAcquireDocumentContentV1WithHttpInfo($extension_id, $worker_name, $body);
        return $response;
    }

    /**
     * Operation aPIAcquireDocumentContentV1WithHttpInfo
     *
     * Acquires a DocumentContent task. The task represents a document to be processed and once acquired, should be processed within the expected execution time. If the task is not completed within the expected time, it will be made available for acquisition by other workers.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  string $worker_name The name of the worker that will process the task. (required)
     * @param  \OpenAPI\Client\Model\V1AcquireDocumentContentRequestV1Body $body (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\V1AcquiredDocumentContentV1|\OpenAPI\Client\Model\RpcStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function aPIAcquireDocumentContentV1WithHttpInfo($extension_id, $worker_name, $body)
    {
        $request = $this->aPIAcquireDocumentContentV1Request($extension_id, $worker_name, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\V1AcquiredDocumentContentV1' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\V1AcquiredDocumentContentV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\OpenAPI\Client\Model\RpcStatus' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\RpcStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\V1AcquiredDocumentContentV1';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AcquiredDocumentContentV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\RpcStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation aPIAcquireDocumentContentV1Async
     *
     * Acquires a DocumentContent task. The task represents a document to be processed and once acquired, should be processed within the expected execution time. If the task is not completed within the expected time, it will be made available for acquisition by other workers.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  string $worker_name The name of the worker that will process the task. (required)
     * @param  \OpenAPI\Client\Model\V1AcquireDocumentContentRequestV1Body $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aPIAcquireDocumentContentV1Async($extension_id, $worker_name, $body)
    {
        return $this->aPIAcquireDocumentContentV1AsyncWithHttpInfo($extension_id, $worker_name, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aPIAcquireDocumentContentV1AsyncWithHttpInfo
     *
     * Acquires a DocumentContent task. The task represents a document to be processed and once acquired, should be processed within the expected execution time. If the task is not completed within the expected time, it will be made available for acquisition by other workers.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  string $worker_name The name of the worker that will process the task. (required)
     * @param  \OpenAPI\Client\Model\V1AcquireDocumentContentRequestV1Body $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aPIAcquireDocumentContentV1AsyncWithHttpInfo($extension_id, $worker_name, $body)
    {
        $returnType = '\OpenAPI\Client\Model\V1AcquiredDocumentContentV1';
        $request = $this->aPIAcquireDocumentContentV1Request($extension_id, $worker_name, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aPIAcquireDocumentContentV1'
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  string $worker_name The name of the worker that will process the task. (required)
     * @param  \OpenAPI\Client\Model\V1AcquireDocumentContentRequestV1Body $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aPIAcquireDocumentContentV1Request($extension_id, $worker_name, $body)
    {
        // verify the required parameter 'extension_id' is set
        if ($extension_id === null || (is_array($extension_id) && count($extension_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $extension_id when calling aPIAcquireDocumentContentV1'
            );
        }
        // verify the required parameter 'worker_name' is set
        if ($worker_name === null || (is_array($worker_name) && count($worker_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $worker_name when calling aPIAcquireDocumentContentV1'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling aPIAcquireDocumentContentV1'
            );
        }

        $resourcePath = '/v1/extensions/{extensionId}/documentContentQueue/{workerName}/acquire';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($extension_id !== null) {
            $resourcePath = str_replace(
                '{' . 'extensionId' . '}',
                ObjectSerializer::toPathValue($extension_id),
                $resourcePath
            );
        }
        // path params
        if ($worker_name !== null) {
            $resourcePath = str_replace(
                '{' . 'workerName' . '}',
                ObjectSerializer::toPathValue($worker_name),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($body)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation aPICompleteDocumentContentV1
     *
     * Completes a DocumentContent task. The task should be marked as complete after successful processing or if an error occurs during processing. If completed successfully, any extracted document attributes should be included in the completion request.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  string $worker_name The name of the worker that processed the task. (required)
     * @param  string $document_content_id The ID of the document content that was processed. (required)
     * @param  \OpenAPI\Client\Model\V1CompleteDocumentContentRequestV1Body $body body (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\V1CompletedDocumentContentV1|\OpenAPI\Client\Model\RpcStatus
     */
    public function aPICompleteDocumentContentV1($extension_id, $worker_name, $document_content_id, $body)
    {
        list($response) = $this->aPICompleteDocumentContentV1WithHttpInfo($extension_id, $worker_name, $document_content_id, $body);
        return $response;
    }

    /**
     * Operation aPICompleteDocumentContentV1WithHttpInfo
     *
     * Completes a DocumentContent task. The task should be marked as complete after successful processing or if an error occurs during processing. If completed successfully, any extracted document attributes should be included in the completion request.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  string $worker_name The name of the worker that processed the task. (required)
     * @param  string $document_content_id The ID of the document content that was processed. (required)
     * @param  \OpenAPI\Client\Model\V1CompleteDocumentContentRequestV1Body $body (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\V1CompletedDocumentContentV1|\OpenAPI\Client\Model\RpcStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function aPICompleteDocumentContentV1WithHttpInfo($extension_id, $worker_name, $document_content_id, $body)
    {
        $request = $this->aPICompleteDocumentContentV1Request($extension_id, $worker_name, $document_content_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\V1CompletedDocumentContentV1' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\V1CompletedDocumentContentV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\OpenAPI\Client\Model\RpcStatus' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\RpcStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\V1CompletedDocumentContentV1';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1CompletedDocumentContentV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\RpcStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation aPICompleteDocumentContentV1Async
     *
     * Completes a DocumentContent task. The task should be marked as complete after successful processing or if an error occurs during processing. If completed successfully, any extracted document attributes should be included in the completion request.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  string $worker_name The name of the worker that processed the task. (required)
     * @param  string $document_content_id The ID of the document content that was processed. (required)
     * @param  \OpenAPI\Client\Model\V1CompleteDocumentContentRequestV1Body $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aPICompleteDocumentContentV1Async($extension_id, $worker_name, $document_content_id, $body)
    {
        return $this->aPICompleteDocumentContentV1AsyncWithHttpInfo($extension_id, $worker_name, $document_content_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aPICompleteDocumentContentV1AsyncWithHttpInfo
     *
     * Completes a DocumentContent task. The task should be marked as complete after successful processing or if an error occurs during processing. If completed successfully, any extracted document attributes should be included in the completion request.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  string $worker_name The name of the worker that processed the task. (required)
     * @param  string $document_content_id The ID of the document content that was processed. (required)
     * @param  \OpenAPI\Client\Model\V1CompleteDocumentContentRequestV1Body $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aPICompleteDocumentContentV1AsyncWithHttpInfo($extension_id, $worker_name, $document_content_id, $body)
    {
        $returnType = '\OpenAPI\Client\Model\V1CompletedDocumentContentV1';
        $request = $this->aPICompleteDocumentContentV1Request($extension_id, $worker_name, $document_content_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aPICompleteDocumentContentV1'
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  string $worker_name The name of the worker that processed the task. (required)
     * @param  string $document_content_id The ID of the document content that was processed. (required)
     * @param  \OpenAPI\Client\Model\V1CompleteDocumentContentRequestV1Body $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aPICompleteDocumentContentV1Request($extension_id, $worker_name, $document_content_id, $body)
    {
        // verify the required parameter 'extension_id' is set
        if ($extension_id === null || (is_array($extension_id) && count($extension_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $extension_id when calling aPICompleteDocumentContentV1'
            );
        }
        // verify the required parameter 'worker_name' is set
        if ($worker_name === null || (is_array($worker_name) && count($worker_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $worker_name when calling aPICompleteDocumentContentV1'
            );
        }
        // verify the required parameter 'document_content_id' is set
        if ($document_content_id === null || (is_array($document_content_id) && count($document_content_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_content_id when calling aPICompleteDocumentContentV1'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling aPICompleteDocumentContentV1'
            );
        }

        $resourcePath = '/v1/extensions/{extensionId}/documentContentQueue/{workerName}/complete/{documentContentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($extension_id !== null) {
            $resourcePath = str_replace(
                '{' . 'extensionId' . '}',
                ObjectSerializer::toPathValue($extension_id),
                $resourcePath
            );
        }
        // path params
        if ($worker_name !== null) {
            $resourcePath = str_replace(
                '{' . 'workerName' . '}',
                ObjectSerializer::toPathValue($worker_name),
                $resourcePath
            );
        }
        // path params
        if ($document_content_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentContentId' . '}',
                ObjectSerializer::toPathValue($document_content_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($body)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation aPICreateDocumentContentV1
     *
     * Creates a new DocumentContent. The DocumentContent represents a document from an external system that needs to be processed.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  \OpenAPI\Client\Model\InlineObject $body body (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\V1DocumentContent|\OpenAPI\Client\Model\RpcStatus
     */
    public function aPICreateDocumentContentV1($extension_id, $body)
    {
        list($response) = $this->aPICreateDocumentContentV1WithHttpInfo($extension_id, $body);
        return $response;
    }

    /**
     * Operation aPICreateDocumentContentV1WithHttpInfo
     *
     * Creates a new DocumentContent. The DocumentContent represents a document from an external system that needs to be processed.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  \OpenAPI\Client\Model\InlineObject $body (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\V1DocumentContent|\OpenAPI\Client\Model\RpcStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function aPICreateDocumentContentV1WithHttpInfo($extension_id, $body)
    {
        $request = $this->aPICreateDocumentContentV1Request($extension_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\V1DocumentContent' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\V1DocumentContent', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\OpenAPI\Client\Model\RpcStatus' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\RpcStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\V1DocumentContent';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1DocumentContent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\RpcStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation aPICreateDocumentContentV1Async
     *
     * Creates a new DocumentContent. The DocumentContent represents a document from an external system that needs to be processed.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  \OpenAPI\Client\Model\InlineObject $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aPICreateDocumentContentV1Async($extension_id, $body)
    {
        return $this->aPICreateDocumentContentV1AsyncWithHttpInfo($extension_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation aPICreateDocumentContentV1AsyncWithHttpInfo
     *
     * Creates a new DocumentContent. The DocumentContent represents a document from an external system that needs to be processed.
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  \OpenAPI\Client\Model\InlineObject $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function aPICreateDocumentContentV1AsyncWithHttpInfo($extension_id, $body)
    {
        $returnType = '\OpenAPI\Client\Model\V1DocumentContent';
        $request = $this->aPICreateDocumentContentV1Request($extension_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'aPICreateDocumentContentV1'
     *
     * @param  string $extension_id The unique ID of the extension. (required)
     * @param  \OpenAPI\Client\Model\InlineObject $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function aPICreateDocumentContentV1Request($extension_id, $body)
    {
        // verify the required parameter 'extension_id' is set
        if ($extension_id === null || (is_array($extension_id) && count($extension_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $extension_id when calling aPICreateDocumentContentV1'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling aPICreateDocumentContentV1'
            );
        }

        $resourcePath = '/v1/extensions/{extensionId}/documentContent';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($extension_id !== null) {
            $resourcePath = str_replace(
                '{' . 'extensionId' . '}',
                ObjectSerializer::toPathValue($extension_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($body)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
