=begin comment

Able API

SDK for building integrations with Able.

The version of the OpenAPI document: 1.20230621235520
Contact: support@able.ai
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('AbleSDK::APIApi');

my $api = AbleSDK::APIApi->new();
isa_ok($api, 'AbleSDK::APIApi');

#
# a_pi_acquire_document_version test
#
{
    my $extension_id = undef; # replace NULL with a proper value
    my $worker_name = undef; # replace NULL with a proper value
    my $properties = undef; # replace NULL with a proper value
    my $result = $api->a_pi_acquire_document_version(extension_id => $extension_id, worker_name => $worker_name, properties => $properties);
}

#
# a_pi_complete_document_version test
#
{
    my $extension_id = undef; # replace NULL with a proper value
    my $worker_name = undef; # replace NULL with a proper value
    my $document_version_id = undef; # replace NULL with a proper value
    my $properties = undef; # replace NULL with a proper value
    my $result = $api->a_pi_complete_document_version(extension_id => $extension_id, worker_name => $worker_name, document_version_id => $document_version_id, properties => $properties);
}

#
# a_pi_create_document_version test
#
{
    my $extension_id = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $result = $api->a_pi_create_document_version(extension_id => $extension_id, body => $body);
}


1;
