/*
 * Able API
 * SDK for building integrations with Able.
 *
 * The version of the OpenAPI document: 1.20230621235520
 * Contact: support@able.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ableai.api.sdk;

import com.ableai.api.ApiException;
import com.ableai.api.sdk.model.InlineObject;
import com.ableai.api.sdk.model.RpcStatus;
import com.ableai.api.sdk.model.V1AcquireDocumentVersionRequestProperties;
import com.ableai.api.sdk.model.V1AcquiredDocumentVersion;
import com.ableai.api.sdk.model.V1CompleteDocumentVersionRequestProperties;
import com.ableai.api.sdk.model.V1CompletedDocumentVersion;
import com.ableai.api.sdk.model.V1DocumentVersion;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiApi
 */
@Ignore
public class ApiApiTest {

    private final ApiApi api = new ApiApi();

    
    /**
     * Acquires a DocumentVersion task. The task represents a document to be processed and once acquired, should be processed within the expected execution time. If the task is not completed within the expected time, it will be made available for acquisition by other workers.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void aPIAcquireDocumentVersionTest() throws ApiException {
        String extensionId = null;
        String workerName = null;
        V1AcquireDocumentVersionRequestProperties properties = null;
        V1AcquiredDocumentVersion response = api.aPIAcquireDocumentVersion(extensionId, workerName, properties);

        // TODO: test validations
    }
    
    /**
     * Completes a DocumentVersion task. The task should be marked as complete after successful processing or if an error occurs during processing. If completed successfully, any extracted document attributes should be included in the completion request.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void aPICompleteDocumentVersionTest() throws ApiException {
        String extensionId = null;
        String workerName = null;
        String documentVersionId = null;
        V1CompleteDocumentVersionRequestProperties properties = null;
        V1CompletedDocumentVersion response = api.aPICompleteDocumentVersion(extensionId, workerName, documentVersionId, properties);

        // TODO: test validations
    }
    
    /**
     * Creates a new DocumentVersion. The DocumentVersion represents a document from an external system that needs to be processed.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void aPICreateDocumentVersionTest() throws ApiException {
        String extensionId = null;
        InlineObject body = null;
        V1DocumentVersion response = api.aPICreateDocumentVersion(extensionId, body);

        // TODO: test validations
    }
    
}
